### ISSUE TITLE
Question: Why `User` model is configured along with `user`?

### ISSUE THREAD

**Issue by eabadjiev** [strongloop/loopback-example-access-control#55]
In `server/model-config.json` we can see:
```json
...
  "User": {
    "dataSource": "db"
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "db",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "db",
    "public": false
  },
  "Role": {
    "dataSource": "db",
    "public": false
  },
  "user": {
    "dataSource": "db",
    "public": true
  }
...
```
, where `User` seems to be redundant. Is there a hidden / obscure purpose it stands for?

**Comment by superkhau** [comment]
`User` is a built-in model and automatically defined when the app is scaffolded. `user` is a custom model we define that extends `User`. We do this to add custom properties because you can't modify the built-in `User` model.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by raymondfeng** [comment]
I disabled the base User from REST - https://github.com/strongloop/loopback-example-access-control/commit/589f8851f31389f5e2186eeb91f161e743ee3f8c

**Comment by superkhau** [comment]
@raymondfeng TY

**Comment by eabadjiev** [comment]
@raymondfeng @superkhau thank you guys.
